main:
        name: 'Name-pwnagotchi'
        whitelist:
                - 'Wifi-1'
                - 'Wifi-2'
    log:
        # file to log to
        path: /var/log/pwnagotchi.log
        rotation:
            enabled: true
            # specify a maximum size to rotate ( format is 10/10B, 10K, 10M 10G )
            size: '10M'

        plugins:
                memtemp:
                        enabled: true
                        scale: fahrenheit
                        orientation: horizontal
                auto-update:
                        enabled: true
                        install: true
                        interval: 1
                grid:
                        enabled: true
                        report: true
                        exclude:
                                - 'Wifi-1'
                                - 'Wifi-2'

ui:
        display:
                enabled: true
                type: 'waveshare_2'
                color: 'black'
                                                     




